task: S2G
device: cpu
do_translation: False
do_recognition: True
data:
  root: ./data/Phoenix-2014-T
  max_len: 256
  dataset_name: Phoenix-2014-T
  input_streams: keypoint
  lowercase: False
  max_sent_length: 256
  joint_parts:
    [
      [11, 12, 13, 14, 15, 16],
      [
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
      ],
      [
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
      ],
      [
        75,
        82,
        85,
        88,
        89,
        92,
        96,
        108,
        112,
        114,
        115,
        121,
        127,
        128,
        129,
        130,
        133,
        136,
        138,
        140,
        141,
        142,
        145,
        153,
        155,
        156,
        157,
        159,
        162,
        163,
        166,
        168,
        170,
        178,
        180,
        182,
        184,
        202,
        207,
        208,
        211,
        219,
        220,
        221,
        223,
        224,
        225,
        227,
        228,
        229,
        230,
        232,
        233,
        234,
        235,
        236,
        237,
        238,
        247,
        248,
        251,
        253,
        256,
        260,
        266,
        309,
        321,
        324,
        326,
        338,
        342,
        344,
        345,
        351,
        357,
        358,
        359,
        360,
        363,
        366,
        368,
        370,
        371,
        372,
        375,
        383,
        385,
        386,
        387,
        389,
        392,
        393,
        396,
        398,
        399,
        407,
        409,
        411,
        413,
        431,
        436,
        437,
        440,
        448,
        449,
        450,
        452,
        453,
        454,
        455,
        456,
        457,
        459,
        460,
        461,
        462,
        463,
        464,
        465,
        472,
        473,
        475,
        477,
        480,
        484,
        490,
        529,
        541,
      ],
    ]
  shuffle: True
  normalize: False
gloss_tokenizer:
  gloss2id_file: ./data/Phoenix-2014-T/gloss2ids.json
  split: " "

testing:
  recognition:
    beam_size: 5
  translation:
training:
  model_dir: ./outputs/SLR/Phoenix-2014T
  validation:
    recognition:
      beam_size: 1
    translation:

  optimization:
    optimizer: Adam
    learning_rate:
      default: 1e-3
    weight_decay: 0.001
    betas:
      - 0.9
      - 0.998
    scheduler: cosineannealing
    t_max: 100
model:
  RecognitionNetwork:
    num_labels: 1120
    body_idx:
      [
        11,
        12,
        13,
        14,
        15,
        16,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        82,
        85,
        88,
        89,
        92,
        96,
        108,
        112,
        114,
        115,
        121,
        127,
        128,
        129,
        130,
        133,
        136,
        138,
        140,
        141,
        142,
        145,
        153,
        155,
        156,
        157,
        159,
        162,
        163,
        166,
        168,
        170,
        178,
        180,
        182,
        184,
        202,
        207,
        208,
        211,
        219,
        220,
        221,
        223,
        224,
        225,
        227,
        228,
        229,
        230,
        232,
        233,
        234,
        235,
        236,
        237,
        238,
        247,
        248,
        251,
        253,
        256,
        260,
        266,
        309,
        321,
        324,
        326,
        338,
        342,
        344,
        345,
        351,
        357,
        358,
        359,
        360,
        363,
        366,
        368,
        370,
        371,
        372,
        375,
        383,
        385,
        386,
        387,
        389,
        392,
        393,
        396,
        398,
        399,
        407,
        409,
        411,
        413,
        431,
        436,
        437,
        440,
        448,
        449,
        450,
        452,
        453,
        454,
        455,
        456,
        457,
        459,
        460,
        461,
        462,
        463,
        464,
        465,
        472,
        473,
        475,
        477,
        480,
        484,
        490,
        529,
        541,
      ]
    left_idx:
      [
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
      ]
    right_idx:
      [
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
      ]
    face_idx:
      [
        75,
        82,
        85,
        88,
        89,
        92,
        96,
        108,
        112,
        114,
        115,
        121,
        127,
        128,
        129,
        130,
        133,
        136,
        138,
        140,
        141,
        142,
        145,
        153,
        155,
        156,
        157,
        159,
        162,
        163,
        166,
        168,
        170,
        178,
        180,
        182,
        184,
        202,
        207,
        208,
        211,
        219,
        220,
        221,
        223,
        224,
        225,
        227,
        228,
        229,
        230,
        232,
        233,
        234,
        235,
        236,
        237,
        238,
        247,
        248,
        251,
        253,
        256,
        260,
        266,
        309,
        321,
        324,
        326,
        338,
        342,
        344,
        345,
        351,
        357,
        358,
        359,
        360,
        363,
        366,
        368,
        370,
        371,
        372,
        375,
        383,
        385,
        386,
        387,
        389,
        392,
        393,
        396,
        398,
        399,
        407,
        409,
        411,
        413,
        431,
        436,
        437,
        440,
        448,
        449,
        450,
        452,
        453,
        454,
        455,
        456,
        457,
        459,
        460,
        461,
        462,
        463,
        464,
        465,
        472,
        473,
        475,
        477,
        480,
        484,
        490,
        529,
        541,
      ]
    net: [
        [256, 256, 1024, 16],
        [256, 256, 1024, 16],
        [256, 256, 1024, 16],
        [256, 256, 1024, 16],
        [256, 256, 1024, 16],
        # [256, 256, 1024, 16],
        # [256, 256, 1024, 16],
        # [256, 256, 1024, 16],
      ]
    activation_dropout: 0.1
    attention_dropout: 0.0
    d_model: 256
    decoder_attention_heads: 16
    decoder_ffn_dim: 512
    decoder_layerdrop: 0.2
    decoder_layers: 8
    dropout: 0.2
    encoder_attention_heads: 16
    encoder_ffn_dim: 512
    encoder_layerdrop: 0.2
    encoder_layers: 8
    max_position_embeddings: 512
    body_visual_head:
      input_size: 256
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
      plus_conv_cfg:
        kernel_size: 3
        stride: 2
        num_layer: 2

    fuse_visual_head:
      input_size: 1024
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
      plus_conv_cfg:
        kernel_size: 3
        stride: 2
        num_layer: 2

    left_visual_head:
      input_size: 512
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
      plus_conv_cfg:
        kernel_size: 3
        stride: 2
        num_layer: 2

    right_visual_head:
      input_size: 512
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
      plus_conv_cfg:
        kernel_size: 3
        stride: 2
        num_layer: 2
    cross_distillation: True
